name: 'bitcoin'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 12  * * *'
jobs:
  GetBtcPrice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'Setup coinmon'
      run: npm install  -g coinmon
    - name: 'Get BTC Price'
      run:  echo "::set-env name=BTCPRICE::$(coinmon -t 1 |  grep BTC  | cut -d ' ' -f 10)"
    - name: Send mail
      if: ${{env.BTCPRICE<secrets.MAX && env.BTCPRICE>secrets.MIN}}
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: 比特币价格监控
        # Literal body:
        body: 价格出现巨大波动,现在的比特币价格是：1BTC=$ ${{env.BTCPRICE}} !
        to: 764666894@qq.com
        from: ${{secrets.MAIL_USERNAME}} # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/plain
