name: 'bitcoin'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/10 * * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Setup python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests lxml
    - name: 'get price'
      run: python bitcoin.py
    - name: 'Send mail'
      run: echo ${{env.sendmail}}
