name: 'bitcoin'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  GetBtcPrice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'Setup coinmon'
      run: npm install  -g coinmon
    - name: 'Get BTC Price'
      run:  echo "::set-env name=BTCPRICE::$(coinmon -t 1 |  grep BTC  | cut -d ' ' -f 10)"
