name: 'bitcoin'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/10 * * * *'
jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup coinmon'
      run: npm install -g coinmon
    - name: 'Get BTC Price'
      run:  echo "::set-env name=BTCPRICE::$(coinmon -t 1 |  grep BTC  | cut -d ' ' -f 10)"
